# Generated by Django 5.0.3 on 2024-08-16 13:07

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashdesk',
            name='transaction_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='cashdesk',
            name='bgn_10',
            field=models.IntegerField(default=50),
        ),
        migrations.AlterField(
            model_name='cashdesk',
            name='bgn_50',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='cashdesk',
            name='eur_10',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='cashdesk',
            name='eur_50',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='cashdesk',
            name='transaction_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
    ]
