# Generated by Django 5.0.3 on 2024-08-16 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_cashdesk_transaction_number_alter_cashdesk_bgn_10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashdesk',
            name='transaction_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, editable=False),
        ),
    ]
