# Generated by Django 5.0.3 on 2024-08-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_transactions_cashoperations'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashoperations',
            name='operation_currency',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashoperations',
            name='bgn_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.AlterField(
            model_name='cashoperations',
            name='eur_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
    ]
